apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    path: argocd/apps
    repoURL: https://github.com/emaaForlin/K8S_Main.git
    targetRevision: main
  destination:
    namespace: default
    name: in-cluster
  syncPolicy:
    automated: {}

