apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: longhorn

resources:
  - https://raw.githubusercontent.com/longhorn/longhorn/v1.2.2/deploy/longhorn.yaml
  - longhorn-ingress.yml

secretGenerator:
- name: basic-auth
  files:
  - ./private/auth
