apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testing

bases:
  - ../../base

commonLabels:
  role: mongo
  environment: testing
patchesStrategicMerge:
  - patch-svc.yml
  - patch-ss.yml
