apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  template:
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:2021.12.1
        resources:
          requests: 
            cpu: "50m"
            memory: "60Mi"
          limits: 
            cpu: "80m"
            memory: "100Mi"
