apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-pv
spec:
  storageClassName: local
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/PiHole/prod/etc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-etc-pv
spec:
  storageClassName: local
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/PiHole/prod/dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-etc-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: local
