apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: mariadb
  labels:
    app: mariadb
spec:
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
      - name: mariadb
        image: mariadb:focal
        resources:
          limits:
            cpu: 150m
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        env:
        - name: MYSQL_DATABASE
          value: nextcloud
        envFrom:
          - secretRef:
              name: nextcloud-db-secret
        volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
          subPath: mysql-data
      terminationGracePeriodSeconds: 30
      volumes:
      - name: db-storage
        persistentVolumeClaim:
          claimName: mariadb-pvc