apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mariadb

resources:
  - 00-ns.yaml
  - 01-daemonset-mariadb.yaml
  - 02-pvc-mariadb.yaml
  - 03-svc-mariadb.yaml

secretGenerator:
  - name: nextcloud-db-secret
    files:
      - MYSQL_ROOT_PASSWORD=./private/db_root.txt
      - MYSQL_USER=./private/username.txt
      - MYSQL_PASSWORD=./private/password.txt
