apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-data
  labels:
    type: local
spec:
  storageClassName: microk8s-hostpath
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/k8s/Pihole"
