apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-pihole-deployment.yaml
  - 01-pihole-svc.yaml 
  - 02-pihole-ingress.yaml 
  - 03-pihole-pv.yaml
  - 04-pihole-pv-claims.yaml

commonLabels:
  app: pihole

