apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: prod-1

bases:
  - ../../base
commonLabels:
  role: mongo
  environment: prod

resources:
  - mongo-prod-svc.yml
patchesStrategicMerge:
  - patch-ss.yml
