apiVersion: v1
kind: Service
metadata:
  name: nfs-svc
spec:
  selector:
    app: nfs
  type: LoadBalancer
  loadBalancerIP: 192.168.0.22
  ports:
    - name: nfs
      port: 2049
      targetPort: 2049
