apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - 00-nfs-deployment.yml
  - 02-nfs-svc.yml

configMapGenerator:
  - name: nfs-exports
    files:
      - ./configs/exports
