apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitoring
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    path: apps/Monitoring
    repoURL: https://github.com/emaaForlin/K8S_Main.git
    targetRevision: main
  destination:
    name: in-cluster
  syncPolicy:
    automated: {}
    syncOptions:
    - Replace=true
