apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    path: apps/NFS/overlays/prod
    repoURL: https://github.com/emaaForlin/K8S_Main.git
    targetRevision: main
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated: {}
