apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    path: apps/PiHole/overlays/prod
    repoURL: git@github.om:emaaForlin/K8S_Main.gitc
    targetRevision: main
  destination:
    name: in-cluster
    namespace: default
  syncPolicy:
    automated: {}
