apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source: 
    path: apps/TestApp
    repoURL: https://github.com/emaaForlin/K8S_Main.git
    targetRevision: main
  destination:
    name: in-cluster

