apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v1.1.2/deploy/static/provider/cloud/deploy.yaml
  - 01-local-storage-class.yaml
patchesStrategicMerge:
  - 00-ingress-svc-patch.yaml
