apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-etc-pv-test
spec:
  storageClassName: local
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/PiHole/etc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-dnsmasq-etc-test
spec:
  storageClassName: local
  capacity:
    storage: 50Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /srv/PiHole/dnsmasq
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-etc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-dnsmasq-etc-test
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: local
