apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: testing 

bases:
  - ../../base

commonLabels:
  app: pihole
  context: testing 

patchesStrategicMerge:
  - 00-pihole-deployment.yaml
  - ingress.yaml
