apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring

#resources:
  #  - ingress.yml

helmCharts:
- name: grafana 
  repo: https://grafana.github.io/helm-charts
  releaseName: grafana  
