apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd
resources:
  - 00-ns-argocd.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - 01-ingress-argocd.yaml
patchesStrategicMerge:
  - 02-deploy-argocd-patch.yaml

